/** C言語の型 */
export const cTypes = [
  /* No.00 */ { name: "void", size: 0 },
  /* No.01 */ { name: "char", size: 1 },
  /* No.02 */ { name: "short", size: 2 },
  /* No.03 */ { name: "int", size: 4 },
  /* No.04 */ { name: "long", size: 4 },
  /* No.05 */ { name: "long long", size: 8 },
  /* No.06 */ { name: "float", size: 4 },
  /* No.07 */ { name: "double", size: 8 },
  /* No.08 */ { name: "unsigned char", size: 1 },
  /* No.09 */ { name: "unsigned short", size: 2 },
  /* No.10 */ { name: "unsigned int", size: 4 },
  /* No.11 */ { name: "unsigned long", size: 4 },
  /* No.12 */ { name: "unsigned long long", size: 8 },
];

export const cTypeIdMap = new Map<string, number>([
  ["void", 0],
  ["char", 1],
  ["signed char", 1],
  ["short", 2],
  ["signed short", 2],
  ["int", 3],
  ["signed int", 3],
  ["long", 4],
  ["signed long", 4],
  ["long int", 4],
  ["signed long int", 4],
  ["long long", 5],
  ["signed long long", 5],
  ["long long int", 5],
  ["signed long long int", 5],
  ["float", 6],
  ["double", 7],
  ["unsigned char", 8],
  ["unsigned short", 9],
  ["unsigned int", 10],
  ["unsigned long", 11],
  ["unsigned long int", 11],
  ["unsigned long long", 12],
  ["unsigned long long int", 12],
]);
